### ISSUE TITLE
Incorrect default parameter passed to AutoLogin::instance

### ISSUE THREAD

**Issue by sanjucta** [deliciousbrains/wp-auto-login#11]
The default value for the $expires parameter causes the site to break . This was inadvertently introduced by [this commit](https://github.com/deliciousbrains/wp-auto-login/commit/4a7d3fd93180b61a07a532cd0cf534fb3416898d#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26)
```
public static function instance( $command_name = 'dbi', $expires = 10_368_000 ) {
        if ( ! isset( self::$instance ) && ! ( self::$instance instanceof AutoLogin ) ) {
            self::$instance = new AutoLogin();
            self::$instance->init( $command_name, $expires );
        }

        return self::$instance;
    }

**Comment by rosswintle** [comment]
Don't know what happened with that first PR. But thanks for fixing, @sanjucta 

I've tagged and created a new release now too.
