### ISSUE TITLE
Add option for single-use link

### ISSUE THREAD

**Issue by rosswintle** [deliciousbrains/wp-auto-login#4]
It would be useful to have an option for a link to be single-use.

I propose that this would involve:

 - Updating the `dbi_get_auto_login_url()` function to add a new 'one-time' flag.
 - Adding database columns:
     -  a boolean to specify that an email should be one-time
     - a datetime to say when the token was last used
 - Updating all the logic

**Comment by polevaultweb** [comment]
> a datetime to say when the token was last used

Do we need that? Would we not just delete the one-time rows when they are used?

**Comment by rosswintle** [comment]
Depends if you want any auditing.

I guess we purge expired keys anyway, so yeah, we can just delete them. 👍
