### ISSUE TITLE
Does specifying an expiry work?

### ISSUE THREAD

**Issue by rosswintle** [deliciousbrains/wp-auto-login#5]
I might be wrong, but I think that the logic for doing the login does not take into account the expiry date set if you specify the fourth parameter?

The only check done is:

```
if ( mysql2date( 'G', $row->created ) < time() - $this->expires ) {
    return false;
}
```

where $this->expires is the default 4-days.

Would be good to write some simple tests and then fix this.

**Comment by polevaultweb** [comment]
Just about to write this issue!

Looks like it never gets set in the DB

![image](https://user-images.githubusercontent.com/1770201/132317450-d3de112c-1e08-443a-8f27-9f5754cd2dc4.png)

**Comment by rosswintle** [comment]
We don't (didn't) specify an expiry so that's expected.

But I'm pretty sure that if we do set an expiry, then it's not used in the login check.

These zeros should also have been purged.

**Comment by polevaultweb** [comment]
We do specify an expiry of 4 months, even the latest links created don't have anything set in the DB for that column

**Comment by rosswintle** [comment]
After discussion, here's the plan for an update:

* Put an expiry in the database for all keys generated, whether they use the default expiry or a specified expiry
* Update logic to check against expiry column in DB (also check for zero and use the default if necessary)
* For DB cleanup, use the expiry set in the DB (and also check for zero and use the default if necessary)
* Move DB cleanup out of `create_key()` - create a DB-CLI command AND call that from wp-cron
* Add an expiry length parameter to the `instance()` instantiator and set this globally for all `create_key()` calls
* Update README
